### ISSUE TITLE
`node:new()` - `id` and `anchor` parameters are ignored

### ISSUE THREAD

**Issue by martin-eden** [rm-code/Graphoon#2]
node.lua: `function Node.new( id, x, y, anchor )`

`id` and `anchor` parameters are ignored.

**Comment by rm-code** [comment]
Hey @martin-eden,

thanks for the report. Do you have code snippet for me? I can't seem to reproduce the issue here.

Did you use

``` lua
graph:addNode( "foo", 10, 10, true )
```

?

Best wishes,
Robert

**Comment by martin-eden** [comment]
False alarm, sorry.

I've done derived work on your code and did not recognize saving `id` and `anchor` in `Node.new`. Now I realized they are saved in closure:

```
function Node.new( id, x, y, anchor )
    ...
    function self:getID()
        return id;
    end
    ...
    return self;
end
```

**Comment by rm-code** [comment]
Ah, no problem!

I use a closure-based approach for OOP in all of my problems... but I know it's not commonly used in the Lua community (at least from what I can tell).

I should try to come up with a better way to allow custom Nodes anyway.

**Comment by martin-eden** [comment]
I think constants in `Node.lua` worth some objectifying to allow outer code pass different values without changing lua source. In that derived work I changed

```
local FORCE_SPRING = 0.005;
local FORCE_CHARGE = 200;
...
```

to 

```
local DEFAULT_WORLD_PARAMS =
{
  force_spring = 0.005;
  force_charge = 200;
  ...
}
```

and made customizable `mass` for any node:

```
node.new = function(a_id, a_x, a_y, a_mass, a_is_anchor, a_world_params)
  ...
  local mass = a_mass or DEFAULT_NODE_MASS
  ...
  local world_params = a_world_params or DEFAULT_WORLD_PARAMS
```

There will be slight performance drop due referencing `world_params` table but I don't consider it critical.

BTW I have wonderful week tinkering with Love and this great algorithm with handy implementation.

**Comment by rm-code** [comment]
@martin-eden Feel free to open a pull request :) 

> BTW I have wonderful week tinkering with Love and this great algorithm with handy implementation.

Glad to hear 👍  Would love to see what you are working on (if it isn't secret of course ^^).

**Comment by martin-eden** [comment]
It's closed-source electric CAD system.

The task was implement force-directed layout algorithm for graph where nodes positions are not initialized (all nodes in zero point).

I've gave a credit in sources to you and Graphoon project. But reformated all code (with my own lua code reformatter, just for fun and to test it on some others code), changed all names from camelCase to lowercase_underscores and made that mentioned structural changes in making overridable constants and customizable node mass.

So there is no much point in pull request - naming is just a matter of personal style and whether or not implement another changes is completely your decision.

I'm glad of your feedback and want to thank you again for implementing this simple and powerful algorithm.

**Comment by martin-eden** [comment]
My constants:

```
local DEFAULT_WORLD_PARAMS =
{
  force_spring = 0.025;
  force_charge = 400;
  max_force = 8;
  node_speed = 16;
  damping_factor = 0.90;
  damping_force = 0.05;
}
```

I've added `damping_force` parameter to avoid nodes jitter and stop flowing separate graph components. Logic is:

```
  local move = function(self, dt)
    if (math.abs(ax) < world_params.damping_force) then
      ax = 0
    end
    if (math.abs(ay) < world_params.damping_force) then
      ay = 0
    end
```

Also I noticed that nullifying node velocities (setting them to 0 in :move()) increases stability but significally increase simulation time (tried and rejected this change).
